#https://dev.to/dariansampare/setting-up-docker-typescript-node-hot-reloading-code-changes-in-a-running-container-2b2f
FROM node-pm2

WORKDIR /logs-checker

COPY ./package*.json ./

RUN npm i

COPY . .

ENV NODE_PATH=./dist

RUN npm run build

CMD ["pm2-runtime", "dist/app.js"]
